Import('env')
core='''lsviewer.cpp window.cpp'''.split()
headers=Glob("*.h")

qrccc = env.Qrc4('resource')
viewer = env.ViewerInstall('lsviewer',core+qrccc,headers, LIBS=['GL','GLU','QtGui','QtCore','QtOpenGL','viewer','meshviewer'])
env.Depends(viewer, Glob('*.glsl'))
