Import('env')
dirs='''
utils
stablefluids
stablefluids_free_surface
flip
fluid
stablefluids_density
stablefluids_viscosity
stablefluids_freesurface_viscosity
darcy
uic
granular
'''.split()
meh='''
darcy
'''.split()


SConscript(dirs=dirs)
