######################################################################
# Automatically generated by qmake (2.01a) Thu Jun 19 18:52:29 2008
######################################################################


# Input
HEADERS +=
SOURCES += main.cpp
LIBS += -lmeshio
INCLUDEPATH += $(EIGEN_PATH) 
#CONFIG += debug
include(../../../app.pro)

