Import('env')

core=''' sim.cpp '''.split()
headers=''' sim.h '''.split()

stablefluids2 = env.SharedLibrary('stablefluids2',core)

env.IncludeInstall(headers)
env.Install(env['LIB_DIR'],stablefluids2)




