Import('env')
core='''bloatviewer.cpp window.cpp'''.split()
headers=Glob("*.h")
qrccc = env.Qrc4('bloatviewer')

viewer = env.ViewerInstall('bloatviewer',core+qrccc,headers, LIBS=['GL','GLU','QtGui','QtCore','QtOpenGL','viewer','meshviewer'])
env.Depends(viewer, Glob('*.glsl'))
