Import('env')




dirs='''
viewerbase
viewershell
meshviewer
lsviewer
lsrangeviewer
gridviewer
viewershell2d
gridviewer2d
macviewer2d
macviewer
'''.split()
needtofix='''
pointviewer
pointviewer2d
meshviewer2d
lsviewer2d


ballviewer
2d
glslviewer
'''.split()


SConscript(dirs=dirs)
