Import('env')

core=''' sim.cpp '''.split()
headers=''' sim.h '''.split()

stablefluids = env.SharedLibrary('stablefluids_freesurface',core)

env.IncludeInstall(headers)
env.Install(env['LIB_DIR'],stablefluids)

SConscript(dirs=['test'])



