Import('env')
core='''pointviewer.cpp window.cpp'''.split()
headers=Glob("*.h")
qrccc = env.Qrc4('pointviewer')

viewer = env.ViewerInstall('pointviewer2d',core+qrccc,headers, LIBS=['GL','GLU','QtGui','QtCore','QtOpenGL','viewer'])
env.Depends(viewer, Glob('*.glsl'))
