Import('env')
core='''gridviewer.cpp window.cpp'''.split()
headers=Glob("*.h")

qrccc = env.Qrc4('shaders/gridviewer')
viewer = env.ViewerInstall('gridviewer2d',core+qrccc,headers,LIBS=['GL','GLU','QtGui','QtCore','QtOpenGL','viewer','GLEW'])
env.Depends(viewer, Glob('*.glsl'))
