import os
env = Environment(CPPPATH=[os.environ['EIGEN_PATH'],'/home/mtao/.local/include'])
test =env.Program('levelsetTest','levelset_test.cpp', LIBS = [], LIBPATH='/home/mtao/.local/lib')
AlwaysBuild(test)
