Import('env')
core=Glob("*.cpp")
headers=Glob("*.h")

qrccc = env.Qrc4('viewershell')
viewer = env.ViewerInstall('viewershell2d',core+qrccc,headers,LIBS=['GL','GLU','GLEW','QtGui','QtCore','QtOpenGL','viewer'])
env.Depends(viewer, Glob('*.glsl'))
